<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'DanLundgren\\DlDanstmpl\\' => array($typo3InstallDir . 'typo3conf/ext/dl_danstmpl/Classes'),
    'DanLundgren\\DlEmailregistration\\' => array($typo3InstallDir . 'typo3conf/ext/dl_emailregistration/Classes'),
    'DanLundgren\\DlMobilebankid\\' => array($typo3InstallDir . 'typo3conf/ext/dl_mobilebankid/Classes'),
    'DanLundgren\\DlPersonalinformation\\' => array($typo3InstallDir . 'typo3conf/ext/dl_personalinformation/Classes'),
    'DanLundgren\\DlRealestate\\' => array($typo3InstallDir . 'typo3conf/ext/dl_realestate/Classes'),
    'DmitryDulepov\\Realurl\\' => array($typo3InstallDir . 'typo3conf/ext/realurl/Classes'),
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder_old/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'Laxap\\BootstrapGrids\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_grids/Classes'),
    'PhpParser\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder_old/Resources/Private/PHP/PHP-Parser/lib/PhpParser'),
    'TeaminmediasPluswerk\\KeSearch\\' => array($typo3InstallDir . 'typo3conf/ext/ke_search/Classes'),
);
